apiVersion: v1
kind: Service
metadata:
  name: my-postgres
spec:
  selector:
    app: postgres
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: appd
spec:
  selector:
    app: appd
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}