name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set_tag.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Set image tag
        id: set_tag
        run: echo "image-tag=latest" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: bash quazictl build --docker

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker image
        run: bash quazictl push